### ISSUE TITLE
Tests in different languages

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/api-management-platform#10]
Testing the default body POST using Javascript gives the following error:
Unable to complete the request

Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server. [Learn more](https://aka.ms/AA4e482)

**Comment by pacharanero** [comment]
Which server instance were you hitting for this? The api.rcpch.ac.uk server instance has CORS enabled in Azure

**Comment by andrewpalmeruk** [comment]
It was when using Dev.rcpch.ac.uk

**Comment by pacharanero** [comment]
dev.rcpch.ac.uk is the developer portal though. It won't respond as the API. It's a website. api.rcpch.ac.uk is where the API is.
Could you perhaps go into some more detail of how you were testing using JS?
Was the code autogenerated from the dev portal? Were you running it on node.js REPL or in the browser console?

**Comment by pacharanero** [comment]
closing this as it appears to have been user error
