### ISSUE TITLE
Logo change needed 

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/api-management-platform#11]
On homepage of (https://dev.rcpch.ac.uk/) update logo to match full one used elsewhere, e.g. https://dev.rcpch.ac.uk/product#product=rcpch-small-business .

**Comment by pacharanero** [comment]
![image](https://user-images.githubusercontent.com/2348385/108191878-8e3eee80-710b-11eb-9fda-1596e0714731.png)
![image](https://user-images.githubusercontent.com/2348385/108191884-90a14880-710b-11eb-82db-f4dcbbe15fee.png)

Now using the correct logo
