### ISSUE TITLE
Design feedback on dev.rcpch.ac.uk

### ISSUE THREAD

**Issue by pacharanero** [rcpch/api-management-platform#12]
Design notes from @kirsten-olson 

- [x] Refer to attached guidance / KSS for colour/font use, etc.

- [x] Recommend using Montserrat font for all styles. Though we’re open to hearing more about use of more standard font for normal text? We note you use Courier (?) for code/links, as standard

- [x] Favour dark blue (#0d0d58) for headings

- [x] The full RCPCH logo in header

- [x] The favicon looks fine. We could rather use the dynamic child icon on a blue background as on our microsites, eg https://childprotection.rcpch.ac.uk/wp-content/uploads/sites/6/2020/05/RCPCH_MICROSITE-favicon-Square-270x270-1.png

- [ ] In the documentation (eg https://dev.rcpch.ac.uk/api-details#api=rcpch-digital-growth-charts-api-server&operation=post-uk-who-calculation) the blue contents on the left side looks good, but will need to change background or font colour as POST and GET not accessible. If we’d like to use Green for some content, we use #66cc33

- [x] We suggest top left can have full logo as shown, and short name such as API platform [check we can include a more complete title for SEO]

- [ ] We like menu, but perhaps suggest:
                                                               i.      Home
                                                             ii.      Explore APIs
                                                           iii.      Subscriptions
                                                           iv.      Log in
                                                             v.      Create account

- [x] Is a footer available? If so, can have some links to main RCPCH site and digital growth charts demo and blog sites, etc. as we do on the blog site

**Comment by pacharanero** [comment]
@kirsten-olson do we mean dark blue #0d0d58 for all headings or just the page topper? Currently I'm just using it for the page top, but it can easily be applied to all `h1`, `h2` ... etc if wanted.

**Comment by pacharanero** [comment]
![image](https://user-images.githubusercontent.com/2348385/102334889-1c212080-3f87-11eb-9054-e02364409cbc.png)

Have sorted favicon and added this 'hero' section, which could do with a nice blue background image... or a banner-friendly photo.

Or..... a selection of traditional growth charts? Would that give instant familiarity with what we're doing here for anyone clinical at least? @kirsten-olson @eatyourpeas

**Comment by kirsten-olson** [comment]
> @kirsten-olson do we mean dark blue #0d0d58 for all headings or just the page topper? Currently I'm just using it for the page top, but it can easily be applied to all `h1`, `h2` ... etc if wanted.

Good point! Our main website uses dark blue for the page title, but charcoal for all heading styles (as well as the main font). I think the colours as you've done are fine.

**Comment by kirsten-olson** [comment]
Hi @pacharanero. On the banner block, @Jo-Ball  should be able to develop some ideas once she's back to work in early January, and considering options for incorporating the current paper growth charts *or* an icon that indicates growth (measuring tape? centile lines?)

 In the meantime, we could try using this as a placeholder: https://www.rcpch.ac.uk/sites/default/files/2020-11/home-page-banner-wallpaper-dynamic-child-blue.png. As on the Child Protection Portal site, it uses a 'wallpaper' style with the 'child' element of our logo.

**Comment by pacharanero** [comment]
That's great - I have incorporated that banner, and it looks great. https://dev.rcpch.ac.uk/

**Comment by pacharanero** [comment]
Footer added - wasn't able to make it look like the ones on our other sites, due to limitation of the API Dev Portal web design tools (wysiwyg yuk)

But it now has a link to the Privacy Policy https://dev.rcpch.ac.uk/privacy

https://dev.rcpch.ac.uk/
