### ISSUE TITLE
Body code is incorrect and fails to POST

### ISSUE THREAD

**Issue by andrewpalmeruk** [rcpch/api-management-platform#9]
The example code:
{
    "birth_date": "2020-04-12T00:00:00.0000000",
    "gestation_days": 4,
    "gestation_weeks": 40,
    "measurement_method": "height",
    "observation_date": "2020-06-12T00:00:00.0000000",
    "observation_value": 60,
    "sex": "male"
}

Should have datetimes rewriting in YYYY-MM-DD format.

**Comment by pacharanero** [comment]
I think this is a bug in Azure's implementation of parsing the openAPI3 spec of our API

In our source code the example is an ISO8601 date in YYYY-MM-DD format:
![image](https://user-images.githubusercontent.com/2348385/108512903-c126e500-72b9-11eb-88fd-79827e4f7696.png)

By the time this is read into Azure, it has been padded out with zeroes as a DateTime
![image](https://user-images.githubusercontent.com/2348385/108513176-21b62200-72ba-11eb-9396-923113322ba7.png)

I checked and other tooling for APIs does not seem to do this.
![image](https://user-images.githubusercontent.com/2348385/108514777-2e3b7a00-72bc-11eb-86ac-ebf3a1deb435.png)
(above example for Postman)

So, we have a few options for fixing this:
* Make the API accept a DateTime as well as an ISO8601 date - it would have to simply discard any Time portion (everything after the `T` in the middle)
* Find some way of fixing it in Azure
* Use a different API Management Platform (if we're going to do this then the time to do it is now, before we have onboarded customers and API keys)

**Comment by andrewpalmeruk** [comment]
Hi @pacharanero 
My inclination would be to go with option 1 (Make the API accept a DateTime as well as an ISO8601 date).
Self-hosting would have to be an absolute last resort (since it requires more maintenance, albeit light-touch), but I do agree that now would be the time to make that change. 

If there are sufficient other reasons to self-host, I'm happy to work with you to get that built.

**Comment by pacharanero** [comment]
closed with rcpch/digital-growth-charts-server#151
